"""Incident evidence package.

One-click bundle of everything an incident investigation (OSHA 300, workers'
comp, insurance) needs for a session: the session summary JSON (with the full
alert log), the per-frame timeline, recording sidecar files, and the video
clip — plus a README that frames what the data is and is not.

A single video is included (overlay preferred — it has the skeleton burned
in, which is what a reviewer actually reads), and only when the whole
package stays under ``EVIDENCE_MAX_MB`` (default 50 MB) so a one-click
download never balloons into a multi-GB transfer.
"""

from __future__ import annotations

import json
import logging
import os
import zipfile
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

# Defaults mirror app/main.py's SESSIONS_DIR resolution.
_SESSIONS_DIR = os.environ.get(
    "SESSIONS_DIR",
    os.path.join(os.path.dirname(__file__), "..", "..", "..", "outputs", "sessions"),
)
_EVIDENCE_DIR = os.environ.get(
    "EVIDENCE_DIR",
    os.path.join(os.path.dirname(__file__), "..", "..", "..", "outputs", "evidence"),
)
_MAX_PACKAGE_MB = float(os.environ.get("EVIDENCE_MAX_MB", "50"))

_LIABILITY = (
    "ERGOVIGILANCE INCIDENT EVIDENCE PACKAGE\n"
    "=======================================\n"
    "Generated by ErgoVigilance (offline, on-premise).\n"
    "\n"
    "WHAT THIS CONTAINS\n"
    "  - session.json      : the session summary (risk distribution, averages,\n"
    "                        and the FULL alert log with trigger rule, severity,\n"
    "                        timestamp, and confidence for every alert)\n"
    "  - recording/        : per-frame timeline, sidecar metadata, and the\n"
    "                        video clip(s) recorded by the workstation camera\n"
    "\n"
    "WHAT THIS IS NOT\n"
    "  Heuristic risk thresholds, not clinically validated, not a medical\n"
    "  device. The posture risk scores are for awareness and prioritization;\n"
    "  they do not establish causation of injury. Use this package as a\n"
    "  starting point for review by a qualified ergonomist or safety\n"
    "  professional.\n"
    "\n"
    "PRIVACY\n"
    "  This package contains video recorded at the workstation. Store it\n"
    "  according to your site's retention policy and worker-consent terms.\n"
)


def _find_session_file(session_id: str) -> Path | None:
    sessions_dir = Path(_SESSIONS_DIR)
    if not sessions_dir.is_dir():
        return None
    # Session files are named session_{ts}_{session_id}.json (clean stops) or
    # session_{ts}_{session_id}.json from crash recovery (same naming).
    for filepath in sessions_dir.glob(f"session_*{session_id}.json"):
        return filepath
    return None


def build_evidence_package(session_id: str) -> dict:
    """Assemble a session's evidence into a zip under outputs/evidence/.

    Returns ``{path, size_bytes, entries, skipped}`` or raises FileNotFoundError
    when the session cannot be located.
    """
    session_file = _find_session_file(session_id)
    if session_file is None:
        raise FileNotFoundError(f"No saved session found for {session_id}")

    entries: list[tuple[str, Path]] = [("session.json", session_file)]

    # Recording sidecar (timeline / summary / observations / video).
    skipped: list[str] = []
    try:
        from app.api.recordings import _find_recording_dir
        rdir = _find_recording_dir(session_id)
    except Exception as exc:  # noqa: BLE001 - sidecar is best-effort
        logger.debug("Recording lookup failed for %s: %s", session_id, exc)
        rdir = None
    if rdir:
        rp = Path(rdir)
        for name in ("timeline.json", "summary.json", "observations.json"):
            p = rp / name
            if p.exists():
                entries.append((f"recording/{name}", p))
        # ONE video, overlay preferred (skeleton burned in = what a reviewer
        # reads); original only when no overlay exists. Included only if the
        # whole package stays under the size cap.
        video = None
        for name in ("overlay.mp4", "original.mp4"):
            p = rp / name
            if p.exists():
                video = (name, p)
                break
        if video is not None:
            name, p = video
            size_mb = p.stat().st_size / (1024 * 1024)
            if size_mb <= _MAX_PACKAGE_MB:
                entries.append((f"recording/{name}", p))
            else:
                skipped.append(f"{name} skipped — too large ({size_mb:.0f} MB, cap {_MAX_PACKAGE_MB:.0f} MB)")

    # README: manifest + liability framing.
    manifest = "\n".join(f"  - {arc}" for arc, _ in entries)
    if skipped:
        manifest += "\n\nSkipped (too large):\n" + "\n".join(f"  - {s}" for s in skipped)
    readme = (
        _LIABILITY
        + "\nCONTENTS\n"
        + manifest
        + "\n\nPACKAGE CREATED\n  "
        + datetime.now().isoformat()
        + "\n"
    )

    out_dir = Path(_EVIDENCE_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = out_dir / f"evidence_{session_id}_{ts}.zip"

    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for arc, src in entries:
            zf.write(src, arc)
        zf.writestr("README.txt", readme)

    return {
        "path": str(out_path),
        "size_bytes": out_path.stat().st_size,
        "entries": [arc for arc, _ in entries] + ["README.txt"],
        "skipped": skipped,
    }
