import type { DemoScenario, AlertItem, AlertEngineState, SystemPerformanceData, ExecutiveDashboardData, DepartmentData, TopIssue, WeeklyTrend } from './types';

function makeAlert(id: string, time: number, level: AlertItem['level'], message: string, explanation: string, notificationTarget: AlertItem['notificationTarget'], suppressed = false, escalated = false): AlertItem {
  const d = new Date(0);
  d.setSeconds(time);
  return {
    id, time: d.toISOString().substring(11, 19) + 'Z',
    level, message, explanation, acknowledged: false,
    suppressed, escalated, notificationTarget,
  };
}

function alertState(overrides: Partial<AlertEngineState>): AlertEngineState {
  return {
    currentLevel: 'none',
    previousLevel: 'none',
    cooldownRemaining: 0,
    escalationLevel: 0,
    duplicateCount: 0,
    totalAlertCount: 0,
    lastAlertTime: 0,
    lastAlertMessage: '',
    lastAlertExplanation: '',
    notificationTarget: 'worker',
    history: [],
    ...overrides,
  };
}

function perfData(overrides: Partial<SystemPerformanceData>): SystemPerformanceData {
  return {
    systemHealth: 'healthy', cpuUsage: 30, memoryUsage: 45, fps: 30,
    cameraStatus: 'active', cameraLatency: 10, detectionLatency: 8,
    processedFrames: 0, droppedFrames: 0, avgProcessingTime: 4,
    peakMemory: 50, uptime: 0, gpuUtilization: 20, aiModelConfidence: 95,
    inferenceTime: 6, lastModelUpdate: '2026-06-28', timeline: [],
    ...overrides,
  };
}

function execData(overrides: Partial<ExecutiveDashboardData>): ExecutiveDashboardData {
  return {
    safetyScore: 80, workersMonitored: 30, highRiskWorkers: 5, mediumRiskWorkers: 10, lowRiskWorkers: 15,
    activeCameras: 28, currentSessions: 24,
    weeklyTrends: [
      { week: 'W23', risk: 38, compliance: 72, alerts: 14 },
      { week: 'W24', risk: 35, compliance: 76, alerts: 12 },
      { week: 'W25', risk: 36, compliance: 74, alerts: 13 },
      { week: 'W26', risk: 32, compliance: 80, alerts: 10 },
      { week: 'W27', risk: 30, compliance: 82, alerts: 9 },
      { week: 'W28', risk: 28, compliance: 85, alerts: 7 },
    ],
    departments: [
      { name: 'Assembly', risk: 45, fatigue: 38, compliance: 72 },
      { name: 'Inspection', risk: 28, fatigue: 22, compliance: 88 },
      { name: 'Warehouse', risk: 55, fatigue: 48, compliance: 65 },
      { name: 'Office', risk: 18, fatigue: 15, compliance: 94 },
      { name: 'Machine Shop', risk: 32, fatigue: 28, compliance: 80 },
    ],
    topIssues: [
      { name: 'Neck Flexion', count: 72, severity: 'high' },
      { name: 'Trunk Flexion', count: 58, severity: 'high' },
      { name: 'Shoulder Elevation', count: 44, severity: 'moderate' },
      { name: 'Poor Standing', count: 31, severity: 'moderate' },
      { name: 'Repetitive Motion', count: 26, severity: 'low' },
    ],
    executiveSummary: 'Factory operating within acceptable safety limits.',
    recommendedActions: ['Schedule worker breaks', 'Adjust workstation ergonomics'],
    overallSafety: 80, compliance: 80, productivity: 78, cameraAvailability: 92, systemHealth: 88, avgRisk: 32, avgFatigue: 28,
    ...overrides,
  };
}

function ts(seconds: number): string {
  const d = new Date(0);
  d.setSeconds(seconds);
  return d.toISOString().substring(11, 19) + 'Z';
}

const baseSessions = [
  { id: 'SESH-2026-06-30-001', date: '2026-06-30', duration: '6h 30m', highestRisk: 'Neck Flexion', task: 'Assembly Line B', status: 'active' as const },
  { id: 'SESH-2026-06-29-003', date: '2026-06-29', duration: '8h 12m', highestRisk: 'Trunk Flexion', task: 'Loading Dock', status: 'completed' as const },
  { id: 'SESH-2026-06-29-002', date: '2026-06-29', duration: '4h 00m', highestRisk: 'Shoulder Elevation', task: 'Quality Control', status: 'completed' as const },
  { id: 'SESH-2026-06-29-001', date: '2026-06-29', duration: '7h 45m', highestRisk: 'Knee Angle', task: 'Fabrication', status: 'completed' as const },
  { id: 'SESH-2026-06-28-005', date: '2026-06-28', duration: '6h 20m', highestRisk: 'Neck Flexion', task: 'Assembly Line A', status: 'completed' as const },
  { id: 'SESH-2026-06-28-004', date: '2026-06-28', duration: '8h 00m', highestRisk: 'Trunk Flexion', task: 'Packaging', status: 'completed' as const },
  { id: 'SESH-2026-06-28-003', date: '2026-06-28', duration: '5h 30m', highestRisk: 'Shoulder Symmetry', task: 'Assembly Line B', status: 'completed' as const },
  { id: 'SESH-2026-06-28-002', date: '2026-06-28', duration: '3h 15m', highestRisk: 'Alignment Deviation', task: 'Inspection', status: 'interrupted' as const },
  { id: 'SESH-2026-06-28-001', date: '2026-06-28', duration: '7h 50m', highestRisk: 'Neck Flexion', task: 'Assembly Line A', status: 'completed' as const },
  { id: 'SESH-2026-06-27-002', date: '2026-06-27', duration: '8h 05m', highestRisk: 'Trunk Flexion', task: 'Loading Dock', status: 'completed' as const },
];

const baseTrends = {
  weeklyTrend: [
    { week: 'W22', averageRisk: 38.2, sessions: 18, incidents: 12 },
    { week: 'W23', averageRisk: 35.7, sessions: 21, incidents: 10 },
    { week: 'W24', averageRisk: 32.4, sessions: 19, incidents: 8 },
    { week: 'W25', averageRisk: 36.1, sessions: 22, incidents: 11 },
    { week: 'W26', averageRisk: 33.8, sessions: 20, incidents: 9 },
    { week: 'W27', averageRisk: 31.2, sessions: 23, incidents: 7 },
    { week: 'W28', averageRisk: 29.5, sessions: 25, incidents: 6 },
    { week: 'W29', averageRisk: 32.4, sessions: 20, incidents: 9 },
  ],
  featureTrends: [
    { feature: 'Neck Flexion', current: 18, previous: 22, change: -18.2 },
    { feature: 'Trunk Flexion', current: 22, previous: 25, change: -12.0 },
    { feature: 'Shoulder Elevation', current: 12, previous: 15, change: -20.0 },
    { feature: 'Shoulder Symmetry', current: 8, previous: 10, change: -20.0 },
    { feature: 'Alignment Deviation', current: 4, previous: 6, change: -33.3 },
    { feature: 'Knee Angle', current: 142, previous: 138, change: 2.9 },
  ],
  riskDistribution: { low: 112, moderate: 18, high: 12 },
};

export function buildSessions(workerId: string, task: string): typeof baseSessions {
  return baseSessions.map((s, i) => i === 0 ? { ...s, id: `SESH-2026-06-30-${workerId}`, task } : s);
}

export const scenarios: DemoScenario[] = [
  {
    id: 'office-worker',
    name: 'Office Worker',
    description: 'Desk-based computer work — neck and shoulder strain from poor monitor height and sustained posture.',
    workerName: 'Elena Rodriguez',
    workerId: 'WA-2104',
    department: 'Admin',
    shift: 'Day (08:00 - 16:00)',
    workstation: 'Workstation 4B',
    experience: '3 years',
    initialContextAwareRisk: {
      currentTask: 'Data Entry',
      workstation: 'Workstation 4B',
      exposureDuration: '0h 00m',
      fatigueLevel: 12,
      contextModifier: 5,
      contextConfidence: 92,
      finalContextRisk: 'low',
      biomechanicalRisk: 'low',
      explanation: 'Good posture maintained. No task or duration modifiers triggered.',
    },
    initialAlertEngine: alertState({
      currentLevel: 'none',
      lastAlertMessage: 'No alerts. Posture within safe range.',
      lastAlertExplanation: 'All biomechanical metrics are within LOW thresholds.',
    }),
    initialSystemPerformance: perfData({
      cpuUsage: 25, memoryUsage: 40, fps: 30, cameraLatency: 12, detectionLatency: 8,
      processedFrames: 7200, droppedFrames: 12, avgProcessingTime: 4.2, peakMemory: 48,
      uptime: 9000, gpuUtilization: 18, aiModelConfidence: 96.5,       inferenceTime: 6.8,
      lastModelUpdate: '2026-06-29',
    }),
    initialExecutiveDashboard: execData({
      safetyScore: 94, workersMonitored: 24, highRiskWorkers: 2, mediumRiskWorkers: 5, lowRiskWorkers: 17,
      activeCameras: 22, currentSessions: 18,
      weeklyTrends: [
        { week: 'W23', risk: 22, compliance: 88, alerts: 4 },
        { week: 'W24', risk: 20, compliance: 90, alerts: 3 },
        { week: 'W25', risk: 24, compliance: 86, alerts: 5 },
        { week: 'W26', risk: 18, compliance: 92, alerts: 2 },
        { week: 'W27', risk: 16, compliance: 94, alerts: 2 },
        { week: 'W28', risk: 14, compliance: 95, alerts: 1 },
      ],
      departments: [
        { name: 'Assembly', risk: 32, fatigue: 28, compliance: 84 },
        { name: 'Inspection', risk: 22, fatigue: 18, compliance: 90 },
        { name: 'Warehouse', risk: 42, fatigue: 38, compliance: 76 },
        { name: 'Office', risk: 12, fatigue: 10, compliance: 96 },
        { name: 'Machine Shop', risk: 26, fatigue: 22, compliance: 86 },
      ],
      topIssues: [
        { name: 'Neck Flexion', count: 18, severity: 'low' },
        { name: 'Shoulder Elevation', count: 12, severity: 'low' },
        { name: 'Trunk Flexion', count: 8, severity: 'low' },
        { name: 'Poor Standing', count: 5, severity: 'low' },
        { name: 'Repetitive Motion', count: 3, severity: 'low' },
      ],
      executiveSummary: 'Factory operating within acceptable safety limits. Office department shows excellent posture compliance (96%).',
      recommendedActions: ['Maintain current ergonomic practices', 'Schedule periodic workstation assessments'],
      overallSafety: 94, compliance: 94, productivity: 88, cameraAvailability: 96, systemHealth: 96, avgRisk: 12, avgFatigue: 18,
    }),
    initialDashboard: {
      session: {
        id: 'SESH-2026-06-30-OFF',
        workerName: 'Elena Rodriguez',
        workerId: 'WA-2104',
        startTime: '2026-06-30T08:00:00Z',
        currentTime: '2026-06-30T10:30:00Z',
        duration: 9000,
        framesAnalyzed: 7200,
        cameraStatus: 'active',
      },
      liveStatus: {
        riskLevel: 'low',
        riskScore: 12,
        confidence: 96.5,
        currentTask: 'Data entry — Reports',
        workerStatus: 'active',
      },
      ergonomicFeatures: [
        { id: 'neck_flexion', name: 'Neck Flexion', value: 8, unit: '°', min: 0, max: 50, status: 'good' },
        { id: 'trunk_flexion', name: 'Trunk Flexion', value: 6, unit: '°', min: 0, max: 60, status: 'good' },
        { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 4, unit: '°', min: 0, max: 90, status: 'good' },
        { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 5, unit: '°', min: 0, max: 90, status: 'good' },
        { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 3, unit: '%', min: 0, max: 30, status: 'good' },
        { id: 'alignment_deviation', name: 'Alignment Deviation', value: 2, unit: '%', min: 0, max: 20, status: 'good' },
        { id: 'knee_angle', name: 'Knee Angle', value: 98, unit: '°', min: 80, max: 180, status: 'good' },
      ],
      issues: [],
      recommendations: {
        worker: 'Maintain current posture. Stand and stretch every 30 minutes.',
        supervisor: 'Workstation ergonomics are adequate.',
      },
      sessionAnalytics: {
        sessionDuration: '2h 30m',
        framesAnalyzed: 7200,
        highestRisk: 'None',
        mostFrequentIssue: 'None',
        averageNeck: 8.2,
        averageTrunk: 6.1,
        averageKnee: 97.8,
      },
      riskHistory: [
        { time: '08:00', value: 10 },
        { time: '08:30', value: 12 },
        { time: '09:00', value: 9 },
        { time: '09:30', value: 14 },
        { time: '10:00', value: 11 },
        { time: '10:30', value: 12 },
      ],
      trendAnalysis: { trend: 'improving', averageRisk: 11.3, sessionsAnalyzed: 42, improving: 28, stable: 12, deteriorating: 2 },
    },
    events: [
      { time: 0, description: 'Worker starts with good posture', delta: { contextAwareRisk: { exposureDuration: '0h 00m', fatigueLevel: 12, contextModifier: 5, contextConfidence: 92, finalContextRisk: 'low' } } },
      { time: 15, description: 'Neck flexion begins as worker focuses on monitor', delta: { liveStatus: { riskLevel: 'low', riskScore: 18 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 14, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 6, unit: '°', min: 0, max: 60, status: 'good' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 4, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 5, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 3, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 2, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 98, unit: '°', min: 80, max: 180, status: 'good' }], contextAwareRisk: { exposureDuration: '0h 15m', fatigueLevel: 15, contextModifier: 5, contextConfidence: 92, finalContextRisk: 'low' }, performance: { cpuUsage: 28, memoryUsage: 42 } } },
      { time: 30, description: 'Shoulder elevation increases from reaching for mouse', delta: { liveStatus: { riskLevel: 'low', riskScore: 25 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 14, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 6, unit: '°', min: 0, max: 60, status: 'good' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 4, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 3, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 2, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 98, unit: '°', min: 80, max: 180, status: 'good' }], issues: [{ id: 'ISS-OW1', severity: 'low', name: 'Minor Shoulder Tension', timestamp: ts(30), detail: 'Right shoulder elevated during sustained mouse use.' }], contextAwareRisk: { exposureDuration: '0h 30m', fatigueLevel: 18, contextModifier: 5, contextConfidence: 93, finalContextRisk: 'low' }, performance: { cpuUsage: 30, memoryUsage: 44, fps: 29 } } },
      { time: 45, description: 'Moderate risk — sustained neck flexion detected', toast: { type: 'warning', title: 'Neck flexion sustained for 30s' }, delta: { performance: { fps: 28, cpuUsage: 32, memoryUsage: 46 }, liveStatus: { riskLevel: 'moderate', riskScore: 38 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 22, unit: '°', min: 0, max: 50, status: 'moderate' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 6, unit: '°', min: 0, max: 60, status: 'good' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 4, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 3, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 2, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 98, unit: '°', min: 80, max: 180, status: 'good' }], contextAwareRisk: { exposureDuration: '0h 45m', fatigueLevel: 22, contextModifier: 5, contextConfidence: 93, finalContextRisk: 'moderate', biomechanicalRisk: 'low', explanation: 'Sustained neck flexion detected. Duration penalty beginning to accumulate from prolonged typing.' }, alertEngine: { currentLevel: 'low', previousLevel: 'none', totalAlertCount: 1, cooldownRemaining: 60, lastAlertTime: 15, lastAlertMessage: 'Minor shoulder tension detected from mouse use.', lastAlertExplanation: 'Right shoulder elevated during sustained mouse use. LOW alert triggered.', notificationTarget: 'worker', history: [makeAlert('AL-OW-01', 15, 'low', 'Minor shoulder tension detected', 'Right shoulder elevated during sustained mouse use. LOW alert triggered.', 'worker')] }, executiveDashboard: { safetyScore: 92, overallSafety: 92 } } },
      { time: 70, description: 'Trunk flexion increases from leaning forward', delta: { liveStatus: { riskLevel: 'moderate', riskScore: 45 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 28, unit: '°', min: 0, max: 50, status: 'moderate' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 14, unit: '°', min: 0, max: 60, status: 'low' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 4, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 3, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 2, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 98, unit: '°', min: 80, max: 180, status: 'good' }], issues: [{ id: 'ISS-OW1', severity: 'low', name: 'Minor Shoulder Tension', timestamp: ts(30), detail: 'Right shoulder elevated during sustained mouse use.' }, { id: 'ISS-OW2', severity: 'moderate', name: 'Forward Head Posture', timestamp: ts(70), detail: 'Head protrudes 5cm past midline. Neck angle at 28°.' }], contextAwareRisk: { exposureDuration: '1h 10m', fatigueLevel: 35, contextModifier: 5, contextConfidence: 94, finalContextRisk: 'moderate', explanation: 'Prolonged screen time — duration penalty increased to 10. Fatigue accumulating from sustained neck flexion above 20°.' }, alertEngine: { currentLevel: 'medium', previousLevel: 'low', escalationLevel: 1, totalAlertCount: 2, cooldownRemaining: 120, lastAlertTime: 70, lastAlertMessage: 'Forward head posture detected — neck angle at 28°.', lastAlertExplanation: 'Sustained neck flexion above 20° with duration penalty active. Escalated to MEDIUM.', notificationTarget: 'worker', history: [makeAlert('AL-OW-01', 15, 'low', 'Minor shoulder tension detected', 'Right shoulder elevated during sustained mouse use. LOW alert triggered.', 'worker'), makeAlert('AL-OW-02', 70, 'medium', 'Forward head posture detected', 'Sustained neck flexion above 20° with duration penalty active. Escalated to MEDIUM.', 'worker')] } } },
      { time: 85, description: 'Worker corrects posture after ergonomic prompt', toast: { type: 'success', title: 'Posture corrected — risk decreasing' }, aiMessage: { time: 85, icon: 'check', text: 'Worker corrected posture. Neck flexion reduced from 28° to 16°.' }, delta: { liveStatus: { riskLevel: 'low', riskScore: 20 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 16, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 8, unit: '°', min: 0, max: 60, status: 'good' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 4, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 6, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 3, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 2, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 98, unit: '°', min: 80, max: 180, status: 'good' }], issues: [{ id: 'ISS-OW1', severity: 'low', name: 'Minor Shoulder Tension', timestamp: ts(30), detail: 'Right shoulder elevated during sustained mouse use.' }], contextAwareRisk: { exposureDuration: '1h 25m', fatigueLevel: 28, contextModifier: 5, contextConfidence: 94, finalContextRisk: 'low', biomechanicalRisk: 'low', explanation: 'Posture corrected. Neck flexion reduced. Fatigue slowly decaying as good posture is maintained.' }, alertEngine: { currentLevel: 'low', previousLevel: 'medium', cooldownRemaining: 60, lastAlertMessage: 'Posture corrected — neck flexion reduced to 16°.', lastAlertExplanation: 'Worker responded to ergonomic prompt. Alert de-escalated to LOW.', notificationTarget: 'worker' }, performance: { cpuUsage: 27, memoryUsage: 42, fps: 30 }, executiveDashboard: { safetyScore: 94, overallSafety: 94 } } },
      { time: 100, description: 'Risk returns to low baseline', delta: { liveStatus: { riskLevel: 'low', riskScore: 14 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 10, unit: '°', min: 0, max: 50, status: 'good' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 6, unit: '°', min: 0, max: 60, status: 'good' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 4, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 6, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 3, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 2, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 98, unit: '°', min: 80, max: 180, status: 'good' }], issues: [], contextAwareRisk: { exposureDuration: '1h 40m', fatigueLevel: 18, contextModifier: 5, contextConfidence: 95, finalContextRisk: 'low' }, alertEngine: { currentLevel: 'none', previousLevel: 'low', cooldownRemaining: 0, lastAlertMessage: 'All clear. Posture within safe range.', lastAlertExplanation: 'All biomechanical metrics returned to LOW thresholds. No alerts active.', notificationTarget: 'worker' }, performance: { cpuUsage: 25, memoryUsage: 40, fps: 30 } } },
    ],
  },
  {
    id: 'assembly-worker',
    name: 'Assembly Line Worker',
    description: 'Repetitive assembly work — neck flexion, trunk asymmetry, and shoulder strain from component fitting.',
    workerName: 'Marcus Thorne',
    workerId: 'WA-4092',
    department: 'Production',
    shift: 'Day (06:00 - 14:00)',
    workstation: 'Station B-12',
    experience: '7 years',
    initialContextAwareRisk: {
      currentTask: 'Assembly',
      workstation: 'Station B-12',
      exposureDuration: '0h 00m',
      fatigueLevel: 35,
      contextModifier: 15,
      contextConfidence: 88,
      finalContextRisk: 'moderate',
      biomechanicalRisk: 'moderate',
      explanation: 'Assembly Work modifier (+15) applied. Repetitive upper limb task elevates baseline risk. Duration penalty not yet active.',
    },
    initialAlertEngine: alertState({
      currentLevel: 'low',
      lastAlertMessage: 'Moderate neck flexion detected at shift start.',
      lastAlertExplanation: 'Baseline neck angle at 18° from looking down at assembly components.',
      history: [makeAlert('AL-AS-00', 0, 'low', 'Moderate neck flexion detected', 'Baseline neck angle at 18° from looking down at assembly components.', 'worker')],
    }),
    initialSystemPerformance: perfData({
      cpuUsage: 45, memoryUsage: 55, fps: 28, cameraLatency: 18, detectionLatency: 12,
      processedFrames: 7920, droppedFrames: 28, avgProcessingTime: 6.5, peakMemory: 62,
      uptime: 9900, gpuUtilization: 32, aiModelConfidence: 94.2,       inferenceTime: 8.2,
      lastModelUpdate: '2026-06-28',
    }),
    initialExecutiveDashboard: execData({
      safetyScore: 78, workersMonitored: 48, highRiskWorkers: 8, mediumRiskWorkers: 15, lowRiskWorkers: 25,
      activeCameras: 42, currentSessions: 36,
      departments: [
        { name: 'Assembly', risk: 48, fatigue: 42, compliance: 70 },
        { name: 'Inspection', risk: 30, fatigue: 24, compliance: 86 },
        { name: 'Warehouse', risk: 52, fatigue: 46, compliance: 68 },
        { name: 'Office', risk: 16, fatigue: 12, compliance: 94 },
        { name: 'Machine Shop', risk: 34, fatigue: 30, compliance: 78 },
      ],
      topIssues: [
        { name: 'Neck Flexion', count: 85, severity: 'high' },
        { name: 'Trunk Flexion', count: 62, severity: 'high' },
        { name: 'Shoulder Elevation', count: 48, severity: 'moderate' },
        { name: 'Poor Standing', count: 28, severity: 'moderate' },
        { name: 'Repetitive Motion', count: 34, severity: 'moderate' },
      ],
      executiveSummary: 'Assembly department shows elevated fatigue (42%). Production line requires ergonomic intervention for neck and trunk flexion.',
      recommendedActions: ['Rotate assembly workers every 2 hours', 'Install adjustable component trays at all stations', 'Schedule ergonomic assessment for Station B-12'],
      overallSafety: 78, compliance: 74, productivity: 82, cameraAvailability: 88, systemHealth: 85, avgRisk: 38, avgFatigue: 32,
    }),
    initialDashboard: {
      session: {
        id: 'SESH-2026-06-30-ASM',
        workerName: 'Marcus Thorne',
        workerId: 'WA-4092',
        startTime: '2026-06-30T06:00:00Z',
        currentTime: '2026-06-30T08:45:00Z',
        duration: 9900,
        framesAnalyzed: 7920,
        cameraStatus: 'active',
      },
      liveStatus: {
        riskLevel: 'moderate',
        riskScore: 42,
        confidence: 94.2,
        currentTask: 'Assembly Line B — Component Fitting',
        workerStatus: 'active',
      },
      ergonomicFeatures: [
        { id: 'neck_flexion', name: 'Neck Flexion', value: 18, unit: '°', min: 0, max: 50, status: 'moderate' },
        { id: 'trunk_flexion', name: 'Trunk Flexion', value: 22, unit: '°', min: 0, max: 60, status: 'moderate' },
        { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' },
        { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' },
        { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 8, unit: '%', min: 0, max: 30, status: 'low' },
        { id: 'alignment_deviation', name: 'Alignment Deviation', value: 4, unit: '%', min: 0, max: 20, status: 'low' },
        { id: 'knee_angle', name: 'Knee Angle', value: 142, unit: '°', min: 80, max: 180, status: 'good' },
      ],
      issues: [
        { id: 'ISS-001', severity: 'high', name: 'Sustained Neck Flexion >30°', timestamp: ts(0), detail: 'Neck flexion exceeded 30° during component fitting.' },
        { id: 'ISS-002', severity: 'moderate', name: 'Trunk Asymmetry During Lift', timestamp: ts(0), detail: 'Trunk rotated 15° off midline during load lift.' },
      ],
      recommendations: {
        worker: 'Adjust workstation height by lowering chair 5cm to reduce neck flexion.',
        supervisor: 'Schedule ergonomic assessment. Consider task rotation every 2 hours.',
      },
      sessionAnalytics: {
        sessionDuration: '2h 45m',
        framesAnalyzed: 7920,
        highestRisk: 'Neck Flexion',
        mostFrequentIssue: 'Trunk Asymmetry',
        averageNeck: 20.4,
        averageTrunk: 22.1,
        averageKnee: 140.2,
      },
      riskHistory: [
        { time: '06:00', value: 22 },
        { time: '06:30', value: 28 },
        { time: '07:00', value: 35 },
        { time: '07:30', value: 40 },
        { time: '08:00', value: 38 },
        { time: '08:30', value: 42 },
      ],
      trendAnalysis: { trend: 'stable', averageRisk: 34.2, sessionsAnalyzed: 128, improving: 45, stable: 62, deteriorating: 21 },
    },
    events: [
      { time: 0, description: 'Worker at moderate risk during assembly', delta: { alertEngine: { currentLevel: 'low', previousLevel: 'none', totalAlertCount: 1, lastAlertTime: 0, lastAlertMessage: 'Moderate neck flexion detected at shift start.', lastAlertExplanation: 'Baseline neck angle at 18° from looking down at assembly components.', notificationTarget: 'worker', history: [makeAlert('AL-AS-00', 0, 'low', 'Moderate neck flexion detected', 'Baseline neck angle at 18° from looking down at assembly components.', 'worker')] } } },
      { time: 10, description: 'Neck flexion increases during precision fitting', delta: { liveStatus: { riskLevel: 'high', riskScore: 55 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 32, unit: '°', min: 0, max: 50, status: 'high' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 22, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 8, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 4, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 142, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'medium', previousLevel: 'low', escalationLevel: 1, totalAlertCount: 2, cooldownRemaining: 120, lastAlertTime: 10, lastAlertMessage: 'Neck flexion increased to 32° during precision fitting.', lastAlertExplanation: 'Neck angle exceeded 30° threshold. Alert escalated to MEDIUM. First shoulder warning issued.', notificationTarget: 'worker', history: [makeAlert('AL-AS-00', 0, 'low', 'Moderate neck flexion detected', 'Baseline neck angle at 18° from looking down at assembly components.', 'worker'), makeAlert('AL-AS-01', 10, 'medium', 'Neck flexion 32° detected', 'Neck angle exceeded 30° threshold. Alert escalated to MEDIUM.', 'worker')] }, performance: { cpuUsage: 50, memoryUsage: 58, fps: 26 } } },
      { time: 20, description: 'High risk alert — neck flexion >30° sustained', toast: { type: 'error', title: 'High Risk: Neck Flexion 32°' }, aiMessage: { time: 20, icon: 'alert', text: 'Neck flexion at 32° for 10+ seconds. Risk of cervical strain if sustained.' }, delta: { liveStatus: { riskLevel: 'high', riskScore: 62 }, issues: [{ id: 'ISS-001', severity: 'high', name: 'Sustained Neck Flexion >30°', timestamp: ts(20), detail: 'Zone C — Assembly. Neck flexion at 32° for 12s.' }, { id: 'ISS-002', severity: 'moderate', name: 'Trunk Asymmetry During Lift', timestamp: ts(0), detail: 'Trunk rotated 15° off midline during load lift.' }, { id: 'ISS-003', severity: 'moderate', name: 'Right Shoulder Elevation Spike', timestamp: ts(20), detail: 'Right shoulder at 28° during overhead reach.' }], alertEngine: { currentLevel: 'high', previousLevel: 'medium', escalationLevel: 2, duplicateCount: 1, totalAlertCount: 3, cooldownRemaining: 180, lastAlertTime: 20, lastAlertMessage: 'SUSTAINED: Neck flexion at 32° for 12s — repeated warning.', lastAlertExplanation: 'Duplicate alert suppressed for same body area. Cooldown prevents notification spam. Escalation level increased.', notificationTarget: 'both', history: [makeAlert('AL-AS-00', 0, 'low', 'Moderate neck flexion detected', 'Baseline neck angle at 18° from looking down at assembly components.', 'worker'), makeAlert('AL-AS-01', 10, 'medium', 'Neck flexion 32° detected', 'Neck angle exceeded 30° threshold. Alert escalated to MEDIUM.', 'worker'), makeAlert('AL-AS-02', 20, 'high', 'Sustained neck flexion 32°', 'Neck flexion at 32° for 12s. Duplicate suppressed. Escalated to HIGH. Supervisor notified.', 'both', false, true)] }, performance: { cpuUsage: 55, memoryUsage: 60, fps: 24 }, executiveDashboard: { safetyScore: 72, overallSafety: 72, avgRisk: 45, highRiskWorkers: 10 } } },
      { time: 35, description: 'Recommendation shown to worker', delta: { recommendations: { worker: 'Lower the component tray by 10cm to reduce neck flexion. Keep elbows at 90° during fitting.', supervisor: 'Install adjustable component tray at Station B-12. Rotate Marcus to Station C for next shift block.' }, alertEngine: { currentLevel: 'high', previousLevel: 'high', cooldownRemaining: 150, lastAlertMessage: 'Supervisor notified — shoulder elevation persists.', lastAlertExplanation: 'Third consecutive shoulder warning. Supervisor notified per escalation protocol.', notificationTarget: 'supervisor' }, performance: { cpuUsage: 52, memoryUsage: 59, fps: 25 } } },
      { time: 50, description: 'Shoulder elevation spike detected', delta: { liveStatus: { riskLevel: 'high', riskScore: 68 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 32, unit: '°', min: 0, max: 50, status: 'high' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 22, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 28, unit: '°', min: 0, max: 90, status: 'moderate' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 8, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 4, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 142, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'high', previousLevel: 'high', duplicateCount: 2, totalAlertCount: 4, cooldownRemaining: 180, lastAlertTime: 50, lastAlertMessage: 'Right shoulder elevation spike — 28° during overhead reach.', lastAlertExplanation: 'Repeated elevated shoulder posture detected. Cooldown prevented duplicate notification. Escalation in progress.', notificationTarget: 'supervisor', history: [makeAlert('AL-AS-00', 0, 'low', 'Moderate neck flexion detected', 'Baseline neck angle at 18° from looking down at assembly components.', 'worker'), makeAlert('AL-AS-01', 10, 'medium', 'Neck flexion 32° detected', 'Neck angle exceeded 30° threshold. Alert escalated to MEDIUM.', 'worker'), makeAlert('AL-AS-02', 20, 'high', 'Sustained neck flexion 32°', 'Neck flexion at 32° for 12s. Duplicate suppressed. Escalated to HIGH. Supervisor notified.', 'both', false, true), makeAlert('AL-AS-03', 50, 'high', 'Shoulder elevation spike 28°', 'Right shoulder at 28° during overhead reach. Repeated warning — cooldown active.', 'supervisor', true, true)] }, performance: { cpuUsage: 60, memoryUsage: 62, fps: 22, droppedFrames: 35 } } },
      { time: 65, description: 'Worker adjusts posture — slight improvement', delta: { liveStatus: { riskLevel: 'moderate', riskScore: 48 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 24, unit: '°', min: 0, max: 50, status: 'moderate' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 22, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 18, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 8, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 4, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 142, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'medium', previousLevel: 'high', cooldownRemaining: 120, lastAlertMessage: 'Worker adjusted posture — shoulder reduced to 18°.', lastAlertExplanation: 'Posture improvement detected. Alert de-escalated from HIGH to MEDIUM.', notificationTarget: 'worker' }, performance: { cpuUsage: 48, memoryUsage: 57, fps: 27 } } },
      { time: 80, description: 'Trunk asymmetry detected during part retrieval', toast: { type: 'warning', title: 'Trunk rotated >15° off midline' }, delta: { liveStatus: { riskLevel: 'moderate', riskScore: 52 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 24, unit: '°', min: 0, max: 50, status: 'moderate' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 28, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 18, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 8, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 4, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 142, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'medium', previousLevel: 'medium', totalAlertCount: 5, cooldownRemaining: 120, lastAlertTime: 80, lastAlertMessage: 'Trunk asymmetry detected — rotated 15° off midline.', lastAlertExplanation: 'Trunk rotated during part retrieval. MEDIUM alert — within cooldown period.', notificationTarget: 'worker', history: [makeAlert('AL-AS-00', 0, 'low', 'Moderate neck flexion detected', 'Baseline neck angle at 18° from looking down at assembly components.', 'worker'), makeAlert('AL-AS-01', 10, 'medium', 'Neck flexion 32° detected', 'Neck angle exceeded 30° threshold. Alert escalated to MEDIUM.', 'worker'), makeAlert('AL-AS-02', 20, 'high', 'Sustained neck flexion 32°', 'Neck flexion at 32° for 12s. Duplicate suppressed. Escalated to HIGH. Supervisor notified.', 'both', false, true), makeAlert('AL-AS-03', 50, 'high', 'Shoulder elevation spike 28°', 'Right shoulder at 28° during overhead reach. Repeated warning — cooldown active.', 'supervisor', true, true), makeAlert('AL-AS-04', 80, 'medium', 'Trunk asymmetry detected', 'Trunk rotated 15° off midline during part retrieval.', 'worker')] }, performance: { cpuUsage: 52, memoryUsage: 58, fps: 25 } } },
      { time: 95, description: 'Risk stabilising as worker adapts', aiMessage: { time: 95, icon: 'trending', text: 'Risk level stabilising. Worker is adapting to ergonomic cues. Recommend break in 20 minutes.' }, delta: { liveStatus: { riskLevel: 'moderate', riskScore: 44 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 20, unit: '°', min: 0, max: 50, status: 'moderate' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 22, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 14, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 8, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 4, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 142, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'medium', previousLevel: 'medium', cooldownRemaining: 60, lastAlertMessage: 'Risk stabilising — worker adapting to ergonomic cues.', lastAlertExplanation: 'No new alerts triggered. Cooldown counting down. Suggest break in 20 minutes.', notificationTarget: 'worker' }, performance: { cpuUsage: 46, memoryUsage: 56, fps: 28 }, executiveDashboard: { safetyScore: 76, overallSafety: 76, avgRisk: 38, highRiskWorkers: 8 } } },
    ],
  },
  {
    id: 'warehouse-worker',
    name: 'Warehouse Worker',
    description: 'Heavy lifting and carrying — trunk flexion, knee angle stress, and high biomechanical load.',
    workerName: 'James Kowalski',
    workerId: 'WA-1099',
    department: 'Logistics',
    shift: 'Day (07:00 - 15:00)',
    workstation: 'Loading Dock 2',
    experience: '5 years',
    initialContextAwareRisk: {
      currentTask: 'Warehouse Loading',
      workstation: 'Loading Dock 2',
      exposureDuration: '0h 00m',
      fatigueLevel: 52,
      contextModifier: 10,
      contextConfidence: 85,
      finalContextRisk: 'high',
      biomechanicalRisk: 'moderate',
      explanation: 'Deep trunk flexion (35°) and knee angle below threshold (68°). Lifting modifier (+10) applied. Significant biomechanical load detected.',
    },
    initialAlertEngine: alertState({
      currentLevel: 'medium',
      totalAlertCount: 1,
      lastAlertTime: 0,
      lastAlertMessage: 'Deep trunk flexion (35°) detected during pallet lift.',
      lastAlertExplanation: 'Trunk flexion at 35° exceeds safe threshold. MEDIUM alert triggered. Lifting modifier (+10) active.',
      notificationTarget: 'worker',
      history: [makeAlert('AL-WH-00', 0, 'medium', 'Deep trunk flexion detected', 'Trunk flexion at 35° exceeds safe threshold. MEDIUM alert triggered.', 'worker')],
    }),
    initialSystemPerformance: perfData({
      cpuUsage: 68, memoryUsage: 72, fps: 26, cameraStatus: 'degraded', cameraLatency: 32, detectionLatency: 18,
      processedFrames: 6480, droppedFrames: 45, avgProcessingTime: 8.8, peakMemory: 82,
      uptime: 8100, gpuUtilization: 52, aiModelConfidence: 91.8,       inferenceTime: 12.4,
      lastModelUpdate: '2026-06-27',
    }),
    initialExecutiveDashboard: execData({
      safetyScore: 62, workersMonitored: 32, highRiskWorkers: 12, mediumRiskWorkers: 14, lowRiskWorkers: 6,
      activeCameras: 26, currentSessions: 28,
      departments: [
        { name: 'Assembly', risk: 48, fatigue: 40, compliance: 72 },
        { name: 'Inspection', risk: 32, fatigue: 26, compliance: 84 },
        { name: 'Warehouse', risk: 62, fatigue: 55, compliance: 58 },
        { name: 'Office', risk: 18, fatigue: 14, compliance: 92 },
        { name: 'Machine Shop', risk: 36, fatigue: 32, compliance: 78 },
      ],
      topIssues: [
        { name: 'Trunk Flexion', count: 96, severity: 'high' },
        { name: 'Neck Flexion', count: 52, severity: 'high' },
        { name: 'Poor Standing', count: 44, severity: 'high' },
        { name: 'Shoulder Elevation', count: 38, severity: 'moderate' },
        { name: 'Repetitive Motion', count: 42, severity: 'moderate' },
      ],
      executiveSummary: 'Warehouse requires urgent ergonomic review. Trunk flexion rates are critical (62% fatigue). Deep lift technique needs retraining.',
      recommendedActions: ['Enforce lifting equipment use for all pallet loads', 'Provide mandatory ergonomic retraining for warehouse staff', 'Install anti-fatigue mats at Loading Dock 2', 'Limit consecutive lifts to 15 per worker'],
      overallSafety: 62, compliance: 58, productivity: 72, cameraAvailability: 68, systemHealth: 72, avgRisk: 52, avgFatigue: 48,
    }),
    initialDashboard: {
      session: {
        id: 'SESH-2026-06-30-WH',
        workerName: 'James Kowalski',
        workerId: 'WA-1099',
        startTime: '2026-06-30T07:00:00Z',
        currentTime: '2026-06-30T09:15:00Z',
        duration: 8100,
        framesAnalyzed: 6480,
        cameraStatus: 'active',
      },
      liveStatus: {
        riskLevel: 'moderate',
        riskScore: 48,
        confidence: 91.8,
        currentTask: 'Loading Dock — Pallet Stacking',
        workerStatus: 'active',
      },
      ergonomicFeatures: [
        { id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'low' },
        { id: 'trunk_flexion', name: 'Trunk Flexion', value: 35, unit: '°', min: 0, max: 60, status: 'high' },
        { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' },
        { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 14, unit: '°', min: 0, max: 90, status: 'low' },
        { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 10, unit: '%', min: 0, max: 30, status: 'low' },
        { id: 'alignment_deviation', name: 'Alignment Deviation', value: 7, unit: '%', min: 0, max: 20, status: 'moderate' },
        { id: 'knee_angle', name: 'Knee Angle', value: 68, unit: '°', min: 80, max: 180, status: 'high' },
      ],
      issues: [
        { id: 'ISS-WH1', severity: 'high', name: 'Deep Trunk Flexion During Lift', timestamp: ts(0), detail: 'Zone A — Loading. Trunk flexion at 35° during pallet lift.' },
        { id: 'ISS-WH2', severity: 'high', name: 'Knee Angle Below Threshold', timestamp: ts(0), detail: 'Right knee at 68° during squat lift — below 90° safe threshold.' },
      ],
      recommendations: {
        worker: 'Use leg muscles for lifting, keep back straight. Avoid twisting during lifts.',
        supervisor: 'Provide lifting belt. Re-train on proper squat technique. Limit consecutive lifts to 15.',
      },
      sessionAnalytics: {
        sessionDuration: '2h 15m',
        framesAnalyzed: 6480,
        highestRisk: 'Trunk Flexion',
        mostFrequentIssue: 'Deep Trunk Flexion',
        averageNeck: 11.2,
        averageTrunk: 32.5,
        averageKnee: 72.4,
      },
      riskHistory: [
        { time: '07:00', value: 35 },
        { time: '07:30', value: 42 },
        { time: '08:00', value: 48 },
        { time: '08:30', value: 45 },
        { time: '09:00', value: 50 },
      ],
      trendAnalysis: { trend: 'deteriorating', averageRisk: 44.0, sessionsAnalyzed: 56, improving: 12, stable: 18, deteriorating: 26 },
    },
    events: [
      { time: 0, description: 'Worker lifting heavy pallets — high trunk flexion', delta: { alertEngine: { currentLevel: 'medium', previousLevel: 'none', totalAlertCount: 1, cooldownRemaining: 120, lastAlertTime: 0, lastAlertMessage: 'Deep trunk flexion (35°) detected during pallet lift.', lastAlertExplanation: 'Trunk flexion at 35° exceeds safe threshold. MEDIUM alert triggered.', notificationTarget: 'worker', history: [makeAlert('AL-WH-00', 0, 'medium', 'Deep trunk flexion detected', 'Trunk flexion at 35° exceeds safe threshold. MEDIUM alert triggered.', 'worker')] } } },
      { time: 10, description: 'Knee angle worsens during deep squat', delta: { liveStatus: { riskLevel: 'high', riskScore: 62 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 35, unit: '°', min: 0, max: 60, status: 'high' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 14, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 10, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 7, unit: '%', min: 0, max: 20, status: 'moderate' }, { id: 'knee_angle', name: 'Knee Angle', value: 62, unit: '°', min: 80, max: 180, status: 'high' }], alertEngine: { currentLevel: 'high', previousLevel: 'medium', escalationLevel: 1, totalAlertCount: 2, cooldownRemaining: 180, lastAlertTime: 10, lastAlertMessage: 'Knee angle dropped to 62° — below safe threshold.', lastAlertExplanation: 'Knee angle below 90° threshold. HIGH alert. Cooldown activated to prevent notification spam.', notificationTarget: 'worker', history: [makeAlert('AL-WH-00', 0, 'medium', 'Deep trunk flexion detected', 'Trunk flexion at 35° exceeds safe threshold. MEDIUM alert triggered.', 'worker'), makeAlert('AL-WH-01', 10, 'high', 'Knee angle 62° — below threshold', 'Knee angle below 90° safe threshold. HIGH alert with cooldown.', 'worker')] }, performance: { cpuUsage: 72, fps: 24 } } },
      { time: 20, description: 'High risk — multiple threshold violations', toast: { type: 'error', title: 'Critical: Trunk 38° + Knee 62°' }, aiMessage: { time: 20, icon: 'alert', text: 'Trunk flexion at 38° and knee angle at 62°. High biomechanical load. Immediate intervention recommended.' }, delta: { liveStatus: { riskLevel: 'high', riskScore: 72 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 38, unit: '°', min: 0, max: 60, status: 'high' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 14, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 10, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 7, unit: '%', min: 0, max: 20, status: 'moderate' }, { id: 'knee_angle', name: 'Knee Angle', value: 62, unit: '°', min: 80, max: 180, status: 'high' }], issues: [{ id: 'ISS-WH1', severity: 'high', name: 'Deep Trunk Flexion During Lift', timestamp: ts(20), detail: 'Zone A — Loading. Trunk at 38°, exceeding safe limit by 8°.' }, { id: 'ISS-WH2', severity: 'high', name: 'Knee Angle Below Threshold', timestamp: ts(20), detail: 'Right knee at 62° during squat lift.' }, { id: 'ISS-WH3', severity: 'moderate', name: 'Asymmetrical Load Distribution', timestamp: ts(20), detail: 'Load shifted to left side — alignment deviation 8cm.' }], alertEngine: { currentLevel: 'critical', previousLevel: 'high', escalationLevel: 2, duplicateCount: 1, totalAlertCount: 3, cooldownRemaining: 300, lastAlertTime: 20, lastAlertMessage: 'CRITICAL: Trunk 38° + Knee 62° — multiple threshold violations.', lastAlertExplanation: 'Cooldown prevented duplicate notification for knee warning. Trunk+ knee combined risk triggers CRITICAL level. Supervisor notified.', notificationTarget: 'both', history: [makeAlert('AL-WH-00', 0, 'medium', 'Deep trunk flexion detected', 'Trunk flexion at 35° exceeds safe threshold. MEDIUM alert triggered.', 'worker'), makeAlert('AL-WH-01', 10, 'high', 'Knee angle 62° — below threshold', 'Knee angle below 90° safe threshold. HIGH alert with cooldown.', 'worker'), makeAlert('AL-WH-02', 20, 'critical', 'Multiple threshold violations', 'Trunk 38° + Knee 62°. CRITICAL alert. Supervisor notified. Cooldown 300s.', 'both', false, true)] }, performance: { cpuUsage: 78, fps: 20, systemHealth: 'degraded', droppedFrames: 52 }, executiveDashboard: { safetyScore: 55, overallSafety: 55, avgRisk: 60, highRiskWorkers: 15 } } },
      { time: 35, description: 'Worker takes brief pause — slight recovery', delta: { liveStatus: { riskLevel: 'moderate', riskScore: 55 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 30, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 14, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 10, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 7, unit: '%', min: 0, max: 20, status: 'moderate' }, { id: 'knee_angle', name: 'Knee Angle', value: 78, unit: '°', min: 80, max: 180, status: 'moderate' }], alertEngine: { currentLevel: 'high', previousLevel: 'critical', cooldownRemaining: 240, lastAlertMessage: 'Recovery detected — trunk reduced to 30°, knee to 78°.', lastAlertExplanation: 'Brief pause improved metrics. CRITICAL de-escalated to HIGH. Cooldown still active.', notificationTarget: 'worker' }, performance: { cpuUsage: 72, fps: 22 } } },
      { time: 55, description: 'Worker resumes lifting with improved form', toast: { type: 'success', title: 'Improved lifting form detected' }, aiMessage: { time: 55, icon: 'check', text: 'Worker using legs for lift. Trunk flexion reduced from 38° to 28°. Continue monitoring.' }, delta: { liveStatus: { riskLevel: 'moderate', riskScore: 42 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 28, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 14, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 10, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 7, unit: '%', min: 0, max: 20, status: 'moderate' }, { id: 'knee_angle', name: 'Knee Angle', value: 92, unit: '°', min: 80, max: 180, status: 'good' }], issues: [{ id: 'ISS-WH1', severity: 'moderate', name: 'Trunk Flexion During Lift', timestamp: ts(55), detail: 'Trunk at 28° — improved but still above baseline.' }, { id: 'ISS-WH2', severity: 'high', name: 'Knee Angle Below Threshold', timestamp: ts(20), detail: 'Right knee at 62° during squat lift.' }], alertEngine: { currentLevel: 'medium', previousLevel: 'high', cooldownRemaining: 120, lastAlertMessage: 'Improved lifting form — trunk reduced to 28°, knee to 92°.', lastAlertExplanation: 'Worker using legs for lift. Cooldown counting down. De-escalated to MEDIUM.', notificationTarget: 'worker' }, performance: { cpuUsage: 65, fps: 24, systemHealth: 'healthy' }, executiveDashboard: { safetyScore: 60, overallSafety: 60, avgRisk: 50, highRiskWorkers: 12 } } },
      { time: 70, description: 'Alignment deviation from uneven load', delta: { liveStatus: { riskLevel: 'moderate', riskScore: 48 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 28, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 14, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 10, unit: '%', min: 0, max: 30, status: 'low' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 9, unit: '%', min: 0, max: 20, status: 'moderate' }, { id: 'knee_angle', name: 'Knee Angle', value: 92, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'medium', previousLevel: 'medium', totalAlertCount: 4, cooldownRemaining: 120, lastAlertTime: 70, lastAlertMessage: 'Alignment deviation 9cm from uneven load.', lastAlertExplanation: 'Load shifted to one side. MEDIUM alert — within cooldown, notification suppressed.', notificationTarget: 'worker', history: [makeAlert('AL-WH-00', 0, 'medium', 'Deep trunk flexion detected', 'Trunk flexion at 35° exceeds safe threshold. MEDIUM alert triggered.', 'worker'), makeAlert('AL-WH-01', 10, 'high', 'Knee angle 62° — below threshold', 'Knee angle below 90° safe threshold. HIGH alert with cooldown.', 'worker'), makeAlert('AL-WH-02', 20, 'critical', 'Multiple threshold violations', 'Trunk 38° + Knee 62°. CRITICAL alert. Supervisor notified. Cooldown 300s.', 'both', false, true), makeAlert('AL-WH-03', 70, 'medium', 'Alignment deviation 9cm', 'Uneven load distribution. MEDIUM — suppressed by cooldown.', 'worker', true, false)] }, performance: { cpuUsage: 68, fps: 22 } } },
      { time: 85, description: 'Break suggested', toast: { type: 'info', title: 'Micro-break recommended in 5 minutes' }, delta: { recommendations: { worker: 'Take a 5-minute break. Stretch lower back and hamstrings. Hydrate.', supervisor: 'Schedule James for a 15-minute rest period. Consider task rotation to inspection.' }, alertEngine: { currentLevel: 'low', previousLevel: 'medium', cooldownRemaining: 60, lastAlertMessage: 'Break suggested — all metrics improving.', lastAlertExplanation: 'Cooldown nearly expired. Suggest break to prevent fatigue accumulation.', notificationTarget: 'worker' }, performance: { cpuUsage: 62, fps: 26 } } },
    ],
  },
  {
    id: 'machine-operator',
    name: 'Machine Operator',
    description: 'Standing machine operation — sustained neck flexion, shoulder elevation, and static posture strain.',
    workerName: 'Chen Wei',
    workerId: 'WA-3381',
    department: 'Production',
    shift: 'Night (22:00 - 06:00)',
    workstation: 'CNC Machine 7',
    experience: '12 years',
    initialContextAwareRisk: {
      currentTask: 'CNC Machining',
      workstation: 'CNC Machine 7',
      exposureDuration: '0h 00m',
      fatigueLevel: 28,
      contextModifier: 5,
      contextConfidence: 90,
      finalContextRisk: 'moderate',
      biomechanicalRisk: 'moderate',
      explanation: 'Sustained neck flexion (20°) from looking down at control panel. Machine Operator modifier (+5) applied for static standing posture.',
    },
    initialAlertEngine: alertState({
      currentLevel: 'low',
      lastAlertMessage: 'Sustained neck flexion (20°) detected at CNC machine.',
      lastAlertExplanation: 'Static standing posture with 20° neck flexion from looking down at control panel.',
      history: [makeAlert('AL-MC-00', 0, 'low', 'Sustained neck flexion detected', 'Static standing posture with 20° neck flexion from looking down at control panel.', 'worker')],
    }),
    initialSystemPerformance: perfData({
      cpuUsage: 38, memoryUsage: 50, fps: 30, cameraLatency: 14, detectionLatency: 10,
      processedFrames: 4320, droppedFrames: 15, avgProcessingTime: 5.0, peakMemory: 55,
      uptime: 5400, gpuUtilization: 22, aiModelConfidence: 93.1,       inferenceTime: 7.5,
      lastModelUpdate: '2026-06-29',
    }),
    initialExecutiveDashboard: execData({
      safetyScore: 82, workersMonitored: 36, highRiskWorkers: 4, mediumRiskWorkers: 10, lowRiskWorkers: 22,
      activeCameras: 32, currentSessions: 28,
      departments: [
        { name: 'Assembly', risk: 40, fatigue: 34, compliance: 76 },
        { name: 'Inspection', risk: 26, fatigue: 20, compliance: 88 },
        { name: 'Warehouse', risk: 48, fatigue: 42, compliance: 70 },
        { name: 'Office', risk: 14, fatigue: 10, compliance: 94 },
        { name: 'Machine Shop', risk: 34, fatigue: 30, compliance: 82 },
      ],
      topIssues: [
        { name: 'Neck Flexion', count: 62, severity: 'moderate' },
        { name: 'Shoulder Elevation', count: 40, severity: 'moderate' },
        { name: 'Trunk Flexion', count: 28, severity: 'low' },
        { name: 'Poor Standing', count: 22, severity: 'low' },
        { name: 'Repetitive Motion', count: 18, severity: 'low' },
      ],
      executiveSummary: 'Machine Shop operating at acceptable safety levels. CNC operators show moderate neck flexion from control panel positioning.',
      recommendedActions: ['Adjust CNC machine platform heights', 'Provide anti-fatigue mats for standing operators', 'Review control panel positioning'],
      overallSafety: 82, compliance: 84, productivity: 80, cameraAvailability: 90, systemHealth: 90, avgRisk: 28, avgFatigue: 24,
    }),
    initialDashboard: {
      session: {
        id: 'SESH-2026-06-30-MCH',
        workerName: 'Chen Wei',
        workerId: 'WA-3381',
        startTime: '2026-06-30T22:00:00Z',
        currentTime: '2026-06-30T23:30:00Z',
        duration: 5400,
        framesAnalyzed: 4320,
        cameraStatus: 'active',
      },
      liveStatus: {
        riskLevel: 'moderate',
        riskScore: 36,
        confidence: 93.1,
        currentTask: 'CNC Machining — Quality Inspection',
        workerStatus: 'active',
      },
      ergonomicFeatures: [
        { id: 'neck_flexion', name: 'Neck Flexion', value: 20, unit: '°', min: 0, max: 50, status: 'moderate' },
        { id: 'trunk_flexion', name: 'Trunk Flexion', value: 10, unit: '°', min: 0, max: 60, status: 'low' },
        { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 16, unit: '°', min: 0, max: 90, status: 'low' },
        { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 18, unit: '°', min: 0, max: 90, status: 'low' },
        { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 5, unit: '%', min: 0, max: 30, status: 'good' },
        { id: 'alignment_deviation', name: 'Alignment Deviation', value: 3, unit: '%', min: 0, max: 20, status: 'good' },
        { id: 'knee_angle', name: 'Knee Angle', value: 172, unit: '°', min: 80, max: 180, status: 'good' },
      ],
      issues: [
        { id: 'ISS-MC1', severity: 'moderate', name: 'Sustained Neck Flexion', timestamp: ts(0), detail: 'Looking down at machine control panel — neck at 20° for extended period.' },
      ],
      recommendations: {
        worker: 'Adjust the control panel angle to reduce downward gaze.',
        supervisor: 'Consider raising the CNC machine platform by 15cm for better visibility.',
      },
      sessionAnalytics: {
        sessionDuration: '1h 30m',
        framesAnalyzed: 4320,
        highestRisk: 'Neck Flexion',
        mostFrequentIssue: 'Neck Strain',
        averageNeck: 18.5,
        averageTrunk: 9.8,
        averageKnee: 170.2,
      },
      riskHistory: [
        { time: '22:00', value: 25 },
        { time: '22:30', value: 30 },
        { time: '23:00', value: 36 },
        { time: '23:30', value: 34 },
      ],
      trendAnalysis: { trend: 'stable', averageRisk: 31.3, sessionsAnalyzed: 89, improving: 32, stable: 44, deteriorating: 13 },
    },
    events: [
      { time: 0, description: 'Operator inspecting machined parts — moderate neck strain', delta: { alertEngine: { currentLevel: 'low', previousLevel: 'none', totalAlertCount: 1, cooldownRemaining: 60, lastAlertTime: 0, lastAlertMessage: 'Sustained neck flexion (20°) detected at CNC machine.', lastAlertExplanation: 'Static standing posture with 20° neck flexion from looking down at control panel.', notificationTarget: 'worker', history: [makeAlert('AL-MC-00', 0, 'low', 'Sustained neck flexion detected', 'Static standing posture with 20° neck flexion from looking down at control panel.', 'worker')] } } },
      { time: 15, description: 'Shoulder elevation increases during precise measurement', delta: { liveStatus: { riskLevel: 'moderate', riskScore: 42 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 25, unit: '°', min: 0, max: 50, status: 'moderate' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 10, unit: '°', min: 0, max: 60, status: 'low' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 16, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 22, unit: '°', min: 0, max: 90, status: 'moderate' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 5, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 3, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 172, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'medium', previousLevel: 'low', escalationLevel: 1, totalAlertCount: 2, cooldownRemaining: 120, lastAlertTime: 15, lastAlertMessage: 'Neck flexion approaching 30° threshold — currently at 25°.', lastAlertExplanation: 'Escalated from LOW to MEDIUM. Neck angle increasing. Shoulder elevation also elevated.', notificationTarget: 'worker', history: [makeAlert('AL-MC-00', 0, 'low', 'Sustained neck flexion detected', 'Static standing posture with 20° neck flexion from looking down at control panel.', 'worker'), makeAlert('AL-MC-01', 15, 'medium', 'Neck flexion 25° — approaching threshold', 'Neck angle increasing. MEDIUM alert. Shoulder elevation also elevated.', 'worker')] }, performance: { fps: 28 } } },
      { time: 28, description: 'Neck flexion increasing — approaching threshold', toast: { type: 'warning', title: 'Neck angle approaching 30° threshold' }, aiMessage: { time: 28, icon: 'alert', text: 'Neck flexion at 28°. Approaching 30° threshold. Raise the inspection platform to reduce bending.' }, delta: { liveStatus: { riskLevel: 'moderate', riskScore: 48 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 28, unit: '°', min: 0, max: 50, status: 'moderate' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 10, unit: '°', min: 0, max: 60, status: 'low' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 16, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 22, unit: '°', min: 0, max: 90, status: 'moderate' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 5, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 3, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 172, unit: '°', min: 80, max: 180, status: 'good' }], issues: [{ id: 'ISS-MC1', severity: 'moderate', name: 'Sustained Neck Flexion', timestamp: ts(28), detail: 'Looking down at machine control panel — neck at 28°.' }, { id: 'ISS-MC2', severity: 'low', name: 'Shoulder Fatigue', timestamp: ts(28), detail: 'Right shoulder elevated at 22° during measurement.' }], alertEngine: { currentLevel: 'high', previousLevel: 'medium', escalationLevel: 2, duplicateCount: 1, totalAlertCount: 3, cooldownRemaining: 180, lastAlertTime: 28, lastAlertMessage: 'CRITICAL: Neck at 28° — sustained elevation requires supervisor intervention.', lastAlertExplanation: 'Repeated neck flexion warning detected. Duplicate suppressed. Escalated to HIGH with supervisor notification.', notificationTarget: 'both', history: [makeAlert('AL-MC-00', 0, 'low', 'Sustained neck flexion detected', 'Static standing posture with 20° neck flexion from looking down at control panel.', 'worker'), makeAlert('AL-MC-01', 15, 'medium', 'Neck flexion 25° — approaching threshold', 'Neck angle increasing. MEDIUM alert. Shoulder elevation also elevated.', 'worker'), makeAlert('AL-MC-02', 28, 'high', 'Neck flexion 28° — supervisor notified', 'Repeated neck flexion warning. Duplicate suppressed. HIGH alert. Supervisor notified.', 'both', false, true)] }, performance: { cpuUsage: 45, fps: 25 }, executiveDashboard: { safetyScore: 78, overallSafety: 78 } } },
      { time: 42, description: 'Operator takes standing break — static strain reduced', delta: { liveStatus: { riskLevel: 'low', riskScore: 28 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 16, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 10, unit: '°', min: 0, max: 60, status: 'low' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 10, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 12, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 5, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 3, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 172, unit: '°', min: 80, max: 180, status: 'good' }], issues: [{ id: 'ISS-MC1', severity: 'low', name: 'Mild Neck Strain', timestamp: ts(42), detail: 'Neck at 16° — reduced after break.' }], alertEngine: { currentLevel: 'low', previousLevel: 'high', cooldownRemaining: 60, lastAlertMessage: 'Break taken — neck reduced to 16°. Static strain relieved.', lastAlertExplanation: 'Operator took standing break. Neck flexion reduced by 43%. De-escalated to LOW.', notificationTarget: 'worker' }, performance: { cpuUsage: 36, fps: 30 }, executiveDashboard: { safetyScore: 82, overallSafety: 82 } } },
      { time: 68, description: 'Operator returns — improved posture noted', aiMessage: { time: 68, icon: 'check', text: 'Posture improved after break. Neck flexion reduced by 37%. Risk decreased from 48 to 30.' }, delta: { liveStatus: { riskLevel: 'low', riskScore: 30 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 18, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 10, unit: '°', min: 0, max: 60, status: 'low' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 16, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 18, unit: '°', min: 0, max: 90, status: 'low' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 5, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 3, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 172, unit: '°', min: 80, max: 180, status: 'good' }], issues: [], alertEngine: { currentLevel: 'none', previousLevel: 'low', cooldownRemaining: 0, lastAlertMessage: 'All clear. Posture improved after break.', lastAlertExplanation: 'No active alerts. Cooldown expired. All metrics within safe range.', notificationTarget: 'worker' }, performance: { cpuUsage: 38, fps: 30 } } },
    ],
  },
  {
    id: 'inspection-worker',
    name: 'Inspection Worker',
    description: 'Detailed quality inspection — prolonged trunk flexion, sustained neck angle, and static standing posture.',
    workerName: 'Priya Sharma',
    workerId: 'WA-6712',
    department: 'Quality',
    shift: 'Day (08:00 - 16:00)',
    workstation: 'Inspection Table 3',
    experience: '4 years',
    initialContextAwareRisk: {
      currentTask: 'PCB Inspection',
      workstation: 'Inspection Table 3',
      exposureDuration: '0h 00m',
      fatigueLevel: 22,
      contextModifier: 5,
      contextConfidence: 91,
      finalContextRisk: 'moderate',
      biomechanicalRisk: 'moderate',
      explanation: 'Sustained trunk flexion (24°) from leaning over inspection table. Inspection modifier (+5) applied. Duration penalty will escalate with prolonged exposure.',
    },
    initialAlertEngine: alertState({
      currentLevel: 'low',
      lastAlertMessage: 'Moderate trunk flexion (24°) from leaning over inspection table.',
      lastAlertExplanation: 'Inspection modifier (+5) applied. Duration penalty will escalate with prolonged exposure.',
      history: [makeAlert('AL-IN-00', 0, 'low', 'Moderate trunk flexion detected', 'Leaning over inspection table — trunk at 24°. LOW alert.', 'worker')],
    }),
    initialSystemPerformance: perfData({
      cpuUsage: 32, memoryUsage: 45, fps: 30, cameraLatency: 10, detectionLatency: 7,
      processedFrames: 5760, droppedFrames: 8, avgProcessingTime: 3.8, peakMemory: 50,
      uptime: 7200, gpuUtilization: 15, aiModelConfidence: 95.0,       inferenceTime: 5.5,
      lastModelUpdate: '2026-06-30',
    }),
    initialExecutiveDashboard: execData({
      safetyScore: 88, workersMonitored: 18, highRiskWorkers: 1, mediumRiskWorkers: 4, lowRiskWorkers: 13,
      activeCameras: 17, currentSessions: 14,
      departments: [
        { name: 'Assembly', risk: 36, fatigue: 30, compliance: 82 },
        { name: 'Inspection', risk: 24, fatigue: 18, compliance: 90 },
        { name: 'Warehouse', risk: 44, fatigue: 38, compliance: 74 },
        { name: 'Office', risk: 14, fatigue: 10, compliance: 94 },
        { name: 'Machine Shop', risk: 28, fatigue: 24, compliance: 84 },
      ],
      topIssues: [
        { name: 'Trunk Flexion', count: 42, severity: 'moderate' },
        { name: 'Neck Flexion', count: 30, severity: 'low' },
        { name: 'Shoulder Elevation', count: 18, severity: 'low' },
        { name: 'Poor Standing', count: 14, severity: 'low' },
        { name: 'Repetitive Motion', count: 8, severity: 'low' },
      ],
      executiveSummary: 'Quality department shows strong compliance (90%). All metrics within acceptable ranges. Continue monitoring trunk flexion during detailed inspection.',
      recommendedActions: ['Provide adjustable PCB holders for Inspection Table 3', 'Schedule rotating micro-breaks every 25 minutes', 'Review standing posture alignment'],
      overallSafety: 88, compliance: 90, productivity: 86, cameraAvailability: 94, systemHealth: 94, avgRisk: 22, avgFatigue: 18,
    }),
    initialDashboard: {
      session: {
        id: 'SESH-2026-06-30-INS',
        workerName: 'Priya Sharma',
        workerId: 'WA-6712',
        startTime: '2026-06-30T08:00:00Z',
        currentTime: '2026-06-30T10:00:00Z',
        duration: 7200,
        framesAnalyzed: 5760,
        cameraStatus: 'active',
      },
      liveStatus: {
        riskLevel: 'moderate',
        riskScore: 34,
        confidence: 95.0,
        currentTask: 'PCB Inspection — Visual Quality Check',
        workerStatus: 'active',
      },
      ergonomicFeatures: [
        { id: 'neck_flexion', name: 'Neck Flexion', value: 16, unit: '°', min: 0, max: 50, status: 'low' },
        { id: 'trunk_flexion', name: 'Trunk Flexion', value: 24, unit: '°', min: 0, max: 60, status: 'moderate' },
        { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 6, unit: '°', min: 0, max: 90, status: 'good' },
        { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 8, unit: '°', min: 0, max: 90, status: 'good' },
        { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 4, unit: '%', min: 0, max: 30, status: 'good' },
        { id: 'alignment_deviation', name: 'Alignment Deviation', value: 5, unit: '%', min: 0, max: 20, status: 'low' },
        { id: 'knee_angle', name: 'Knee Angle', value: 168, unit: '°', min: 80, max: 180, status: 'good' },
      ],
      issues: [
        { id: 'ISS-IN1', severity: 'moderate', name: 'Prolonged Trunk Flexion', timestamp: ts(0), detail: 'Leaning over inspection table — trunk at 24° for 20+ minutes.' },
      ],
      recommendations: {
        worker: 'Adjust standing height. Bring work closer to eye level.',
        supervisor: 'Provide adjustable-height inspection table. Consider magnifying lamp to reduce leaning.',
      },
      sessionAnalytics: {
        sessionDuration: '2h 00m',
        framesAnalyzed: 5760,
        highestRisk: 'Trunk Flexion',
        mostFrequentIssue: 'Forward Lean',
        averageNeck: 15.2,
        averageTrunk: 22.8,
        averageKnee: 166.5,
      },
      riskHistory: [
        { time: '08:00', value: 22 },
        { time: '08:30', value: 28 },
        { time: '09:00', value: 34 },
        { time: '09:30', value: 32 },
      ],
      trendAnalysis: { trend: 'stable', averageRisk: 29.0, sessionsAnalyzed: 73, improving: 25, stable: 38, deteriorating: 10 },
    },
    events: [
      { time: 0, description: 'Inspector examining PCBs — moderate trunk lean', delta: { alertEngine: { currentLevel: 'low', previousLevel: 'none', totalAlertCount: 1, cooldownRemaining: 60, lastAlertTime: 0, lastAlertMessage: 'Moderate trunk flexion (24°) from leaning over inspection table.', lastAlertExplanation: 'Inspection modifier (+5) applied. Duration penalty will escalate with prolonged exposure.', notificationTarget: 'worker', history: [makeAlert('AL-IN-00', 0, 'low', 'Moderate trunk flexion detected', 'Leaning over inspection table — trunk at 24°. LOW alert.', 'worker')] } } },
      { time: 12, description: 'Trunk flexion increases during detailed inspection', delta: { liveStatus: { riskLevel: 'moderate', riskScore: 40 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 16, unit: '°', min: 0, max: 50, status: 'low' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 28, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 6, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 8, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 4, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 5, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 168, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'medium', previousLevel: 'low', escalationLevel: 1, totalAlertCount: 2, cooldownRemaining: 120, lastAlertTime: 12, lastAlertMessage: 'Trunk flexion increased to 28° — prolonged inspection posture.', lastAlertExplanation: 'Duration penalty escalating. MEDIUM alert triggered. Cooldown activated.', notificationTarget: 'worker', history: [makeAlert('AL-IN-00', 0, 'low', 'Moderate trunk flexion detected', 'Leaning over inspection table — trunk at 24°. LOW alert.', 'worker'), makeAlert('AL-IN-01', 12, 'medium', 'Trunk flexion 28° — prolonged duration', 'Duration penalty escalating. MEDIUM alert. Cooldown activated.', 'worker')] }, performance: { cpuUsage: 36, memoryUsage: 48 } } },
      { time: 25, description: 'Neck flexion also increasing', toast: { type: 'warning', title: 'Trunk approaching 30° threshold' }, aiMessage: { time: 25, icon: 'alert', text: 'Trunk flexion at 30°. Leaning forward to inspect PCBs. Raise work surface to reduce bending.' }, delta: { liveStatus: { riskLevel: 'moderate', riskScore: 46 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 20, unit: '°', min: 0, max: 50, status: 'moderate' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 30, unit: '°', min: 0, max: 60, status: 'moderate' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 6, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 8, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 4, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 5, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 168, unit: '°', min: 80, max: 180, status: 'good' }], issues: [{ id: 'ISS-IN1', severity: 'moderate', name: 'Prolonged Trunk Flexion', timestamp: ts(25), detail: 'Leaning over inspection table — trunk at 30°.' }, { id: 'ISS-IN2', severity: 'low', name: 'Neck Strain from Downward Gaze', timestamp: ts(25), detail: 'Neck at 20° from looking down at PCB details.' }], alertEngine: { currentLevel: 'high', previousLevel: 'medium', escalationLevel: 2, duplicateCount: 1, totalAlertCount: 3, cooldownRemaining: 180, lastAlertTime: 25, lastAlertMessage: 'HIGH: Trunk at 30° — prolonged exposure escalation.', lastAlertExplanation: 'Inspection duration exceeded threshold. Duplicate suppressed. Escalated to HIGH. Supervisor notified.', notificationTarget: 'both', history: [makeAlert('AL-IN-00', 0, 'low', 'Moderate trunk flexion detected', 'Leaning over inspection table — trunk at 24°. LOW alert.', 'worker'), makeAlert('AL-IN-01', 12, 'medium', 'Trunk flexion 28° — prolonged duration', 'Duration penalty escalating. MEDIUM alert. Cooldown activated.', 'worker'), makeAlert('AL-IN-02', 25, 'high', 'Trunk 30° — prolonged exposure', 'Inspection duration exceeded threshold. Duplicate suppressed. HIGH alert. Supervisor notified.', 'both', false, true)] }, performance: { cpuUsage: 40, fps: 28 }, executiveDashboard: { safetyScore: 84, overallSafety: 84 } } },
      { time: 38, description: 'Recommendation to adjust work height', delta: { recommendations: { worker: 'Raise the PCB holder by 12cm to reduce trunk bending. Use a magnifying glass instead of leaning forward.', supervisor: 'Provide adjustable PCB holder and magnifying lamp for Inspection Table 3.' }, alertEngine: { currentLevel: 'high', previousLevel: 'high', cooldownRemaining: 150, lastAlertMessage: 'Supervisor notified — workstation adjustment recommended.', lastAlertExplanation: 'Supervisor notification sent. Adjustable PCB holder and magnifying lamp recommended.', notificationTarget: 'supervisor' }, performance: { cpuUsage: 38, fps: 29 } } },
      { time: 52, description: 'Worker adjusts posture after prompt', toast: { type: 'success', title: 'Posture corrected — trunk reduced 33%' }, aiMessage: { time: 52, icon: 'check', text: 'Worker raised the PCB holder. Trunk flexion decreased from 30° to 18°. Much safer working angle.' }, delta: { liveStatus: { riskLevel: 'low', riskScore: 26 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'good' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 18, unit: '°', min: 0, max: 60, status: 'low' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 6, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 8, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 4, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 5, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 168, unit: '°', min: 80, max: 180, status: 'good' }], issues: [{ id: 'ISS-IN1', severity: 'low', name: 'Mild Trunk Flexion', timestamp: ts(52), detail: 'Trunk at 18° — within acceptable range after adjustment.' }], alertEngine: { currentLevel: 'low', previousLevel: 'high', cooldownRemaining: 60, lastAlertMessage: 'Posture corrected — trunk reduced from 30° to 18°.', lastAlertExplanation: 'Worker raised PCB holder. De-escalated from HIGH to LOW. Cooldown counting down.', notificationTarget: 'worker' }, performance: { cpuUsage: 34, fps: 30 }, executiveDashboard: { safetyScore: 88, overallSafety: 88 } } },
      { time: 68, description: 'Alignment deviation from asymmetrical stance', delta: { liveStatus: { riskLevel: 'low', riskScore: 30 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'good' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 18, unit: '°', min: 0, max: 60, status: 'low' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 6, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 8, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 4, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 6, unit: '%', min: 0, max: 20, status: 'low' }, { id: 'knee_angle', name: 'Knee Angle', value: 168, unit: '°', min: 80, max: 180, status: 'good' }], alertEngine: { currentLevel: 'low', previousLevel: 'low', totalAlertCount: 4, cooldownRemaining: 60, lastAlertTime: 68, lastAlertMessage: 'Alignment deviation 6cm — minor asymmetry.', lastAlertExplanation: 'Minor alignment deviation detected. LOW alert — within cooldown period.', notificationTarget: 'worker', history: [makeAlert('AL-IN-00', 0, 'low', 'Moderate trunk flexion detected', 'Leaning over inspection table — trunk at 24°. LOW alert.', 'worker'), makeAlert('AL-IN-01', 12, 'medium', 'Trunk flexion 28° — prolonged duration', 'Duration penalty escalating. MEDIUM alert. Cooldown activated.', 'worker'), makeAlert('AL-IN-02', 25, 'high', 'Trunk 30° — prolonged exposure', 'Inspection duration exceeded threshold. Duplicate suppressed. HIGH alert. Supervisor notified.', 'both', false, true), makeAlert('AL-IN-03', 68, 'low', 'Alignment deviation 6cm', 'Minor asymmetry from uneven stance.', 'worker')] }, performance: { cpuUsage: 35 } } },
      { time: 82, description: 'Steady state — good posture maintained', toast: { type: 'success', title: 'All metrics within safe range' }, delta: { liveStatus: { riskLevel: 'low', riskScore: 22 }, ergonomicFeatures: [{ id: 'neck_flexion', name: 'Neck Flexion', value: 12, unit: '°', min: 0, max: 50, status: 'good' }, { id: 'trunk_flexion', name: 'Trunk Flexion', value: 18, unit: '°', min: 0, max: 60, status: 'low' }, { id: 'left_shoulder_elev', name: 'Left Shoulder Elevation', value: 6, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'right_shoulder_elev', name: 'Right Shoulder Elevation', value: 8, unit: '°', min: 0, max: 90, status: 'good' }, { id: 'shoulder_symmetry', name: 'Shoulder Symmetry', value: 4, unit: '%', min: 0, max: 30, status: 'good' }, { id: 'alignment_deviation', name: 'Alignment Deviation', value: 3, unit: '%', min: 0, max: 20, status: 'good' }, { id: 'knee_angle', name: 'Knee Angle', value: 168, unit: '°', min: 80, max: 180, status: 'good' }], issues: [], alertEngine: { currentLevel: 'none', previousLevel: 'low', cooldownRemaining: 0, lastAlertMessage: 'All clear. All metrics within safe range.', lastAlertExplanation: 'No active alerts. Cooldown expired. Good posture maintained.', notificationTarget: 'worker' }, performance: { cpuUsage: 32, fps: 30 } } },
    ],
  },
];

export function getScenario(id: string): DemoScenario | undefined {
  return scenarios.find((s) => s.id === id);
}
