[logger]
level = "info"

[client]
showErrorDetails = true

[server]
headless = true
port = 8501

[theme]
primaryColor = "#16803c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#1f2937"
font = "sans serif"
